### ISSUE TITLE
Registration Toolkit (LandmarkRegistration) "Static"/Distortion output with .tif input file

### ISSUE THREAD

**Issue by ztan-io** [viscenter/registration-toolkit#1]
When using the following input files (both items shown in "input_files_scrnshot.tiff"), I receive distortion-like output. A screenshot of the outputted image file is attached and titled "output_scrnshot.png". I have also attached the properties of the moving image (properties_tif.txt) and the output from the console when running the LandmarkRegistration program (console.log)

Below is the command I used to run LandmarkRegistration:
`./LandmarkRegistration landmarks.txt ~/Desktop/.../static_image.jpg ~/Desktop/moving_image.tif ~/Desktop/output_image.tif ~/Desktop/transform 100`

_**NOTE:** Once I converted the moving_image from a .tif to a .jpg, the program worked as expected_ 

**Attached files for this issue:**
[Archive.zip](https://github.com/viscenter/registration-toolkit/files/476814/Archive.zip)

**Comment by csparker247** [comment]
This is likely fixed after the big refactor into `rt_register2d`. Need to confirm.

**Comment by csparker247** [comment]
Should be fixed by #23
