### ISSUE TITLE
Disegni-Image-Segmenter

### ISSUE THREAD

**Issue by Samu100** [viscenter/registration-toolkit#42]
This is the fusion of all the work that I've been doing with image segmentation. It involves the Watershed Segmentation along with the Otsu Segmentation.

**Comment by Samu100** [comment]
[ITK Semi-Auto Research.docx](https://github.com/viscenter/registration-toolkit/files/4256984/ITK.Semi-Auto.Research.docx)

**Comment by csparker247** [comment]
The functionality enabled in #45 is sufficient for this task.
